language: julia

os:
  - osx
  - linux
julia: "1.3"

jobs:
  allow_failures:  # Allow to fail on nightly
    - julia: nightly
  include:
    - julia: nightly
      os: linux

notifications:
  email: false
