name = "Libxc"
uuid = "66e17ffc-8502-11e9-23b5-c9248d0eb96d"
authors = ["Jason Eu <morty.yu@yahoo.com>"]
version = "0.1.3"

[deps]
Libxc_jll = "a56a6d9d-ad03-58af-ab61-878bf78270d6"

[compat]
Libxc_jll = "4.3"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
